### ISSUE TITLE
Add nuke. "Explodes" the swirls. Gets rid of all the swirls and adds up points.

### ISSUE THREAD

**Issue by LuiAlva** [LuiAlva/SwirlyTap#32]
implemented by having counters for each swirl currently on the screen and adding all type of points and time. Can include all red swirls.
Can also use the Arrays to make swirls disappear.
Can totally work with 2 player for stealing points.

**Comment by spencernewell93** [comment]
Great idea!

**Comment by LuiAlva** [comment]
Working model complete.
