### ISSUE TITLE
Swirls do not disappear when tapped (or after x seconds)

### ISSUE THREAD

**Issue by Diana-Pham** [LuiAlva/SwirlyTap#4]
Ideal:  After a swirl appears, if the user taps it within x seconds, they gain a point and the swirl disappears.  If the user does not tap it within x seconds, it still disappears and the user loses their chance for a point added to their score.

Reality:  Swirls don't disappear.

**Comment by spencernewell93** [comment]
Ill be working on this tonight. With the weather like it is we will just
play it by ear. When the roads clear up we can schedule our  next meeting

**Comment by LuiAlva** [comment]
I have set it up for the swirl to disappear and give or lose a point on click.
Still need to make them disappear after x sec.

**Comment by Diana-Pham** [comment]
Spencer has implemented the disappearing swirls after no-click.  Nice job, guys!
