### ISSUE TITLE
Short sound when Good Swirl (or Bad Swirl) is tapped

### ISSUE THREAD

**Issue by Diana-Pham** [LuiAlva/SwirlyTap#9]
Add a short sound when a swirl is clicked to add aural confirmation of a tapped swirl.
Sounds for a good swirl should be different than for a bad swirl.  
Maybe high tonal sound for good swirl, and low tone for bad swirl?

**Comment by spencernewell93** [comment]
gunna make a 2x button

**Comment by Diana-Pham** [comment]
Finished.  Feel free to change the sounds; they're merely placeholders.
